apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- name: mpod.kb.io
  objectSelector:
    matchExpressions:
    - key: component
      operator: NotIn
      values:
      - kruise-manager
      - asi-extensions-webhook
    - key:  skip-webhook.alibabacloud.com/kruise
      operator: NotIn
      values:
      - 'true'
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- name: vpod.kb.io
  objectSelector:
    matchExpressions:
    - key: component
      operator: NotIn
      values:
      - kruise-manager
      - asi-extensions-webhook
    - key: skip-webhook.alibabacloud.com/kruise
      operator: NotIn
      values:
      - 'true'
- name: vpodeviction.kb.io
  objectSelector:
    matchExpressions:
    - key: component
      operator: NotIn
      values:
      - kruise-manager
      - asi-extensions-webhook
    - key: skip-webhook.alibabacloud.com/kruise
      operator: NotIn
      values:
      - 'true'
